### PR TITLE
signup/abuse: Tweak the rate-limiting parameters

### LINKED ISSUE #12: abuse/signup: The rate-limiting formula is wrong
Currently, the proposed rate-limiting formula has a “tiny” bug: it yields ridiculously low request rates per `/32`, which cripples the whole thing.

I think the dependency on the network size might have to be more subtle, but I need to figure out the maths for this.

### PR DESCRIPTION
**Pull request by KellerFuchs**
Closes #12

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Does that seem legit?

**Comment by KellerFuchs** [comment]
Ran the numbers for `α = 20%` and `r = 200`:

| t\s | 24 | 20 | 16 | 10 | 8 |
| --- | --- | --- | --- | --- | --- |
| 1 | 8 | 13 | 22 | 51 | 66 |
| 2 | 15 | 26 | 44 | 101 | 132 |
| 3 | 22 | 38 | 66 | 151 | 198 |
| 4 | 29 | 51 | 88 | 201 | 264 |
| 5 | 36 | 63 | 109 | 251 | 330 |
| 6 | 44 | 76 | 131 | 301 | 396 |
| 7 | 51 | 88 | 153 | 351 | 462 |
| 14 | 101 | 176 | 305 | 701 | 924 |
| 31 | 223 | 388 | 675 | 1551 | 2046 |
| 60 | 431 | 751 | 1306 | 3001 | 3959 |
| 120 | 862 | 1501 | 2612 | 6001 | 7918 |
| 365 | 2621 | 4563 | 7944 | 18251 | 24082 |

This seems kinda legit for how things depent on the network size.
Now, let's figure out the time-damping.

**Comment by KellerFuchs** [comment]
OK, having a first try at time-damping, with `r = 10`, `α = 30%` and `β = 20`:

| t\s | 24 | 20 | 16 | 10 | 8 | Internet |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 2 | 4 | 8 | 27 | 40 | 10200 |
| 2 | 2 | 4 | 8 | 27 | 41 | 10455 |
| 3 | 2 | 4 | 8 | 28 | 42 | 10710 |
| 4 | 2 | 4 | 9 | 29 | 43 | 10965 |
| 5 | 2 | 4 | 9 | 30 | 45 | 11475 |
| 6 | 2 | 4 | 9 | 31 | 47 | 11985 |
| 7 | 2 | 4 | 10 | 32 | 48 | 12240 |
| 14 | 3 | 5 | 12 | 40 | 60 | 15300 |
| 31 | 4 | 8 | 18 | 60 | 91 | 23205 |
| 60 | 6 | 12 | 28 | 96 | 145 | 36975 |
| 120 | 10 | 22 | 49 | 170 | 258 | 65790 |
| 365 | 26 | 60 | 137 | 475 | 720 | 183600 |

We have an average rate of 20 signups/day, yet we can absorb a 10000 signup spike in a single day (uniformly spread over the whole Internet, likely much less). Note that this is only meant to prevent repeated abuse from a (more-or-less) fixed set of IPs, not to prevent resource exhaustion on the shell servers during a “Slashdot” event.

**Comment by KellerFuchs** [comment]
@hashbang/administrators @hashbang/contributers Penny for your thoughts?

**Comment by lrvick** [comment]
Those numbers look pretty reasonable, provided we can make some kind of white-list for people that may be teaching classes with our setup (legitimate bulk account creation from a single ip all at once).

**Comment by lrvick** [comment]
+1 to merge whenever

**Pull request merged**
