### PR TITLE
Add link to hashbangctl

### PR DESCRIPTION
**Pull request by napcae**
Also see [this PR](https://github.com/hashbang/hashbangctl/pull/19).

### CODE REVIEW

**Comment by daurnimator** [comment]
Please keep two newlines at the end of a section.

**Review by daurnimator — APPROVED** [review]
Please squash your commits so we merge the same commits you have.

**Comment by KellerFuchs** [comment]
@napcae Why did you close the PR?

**Comment by KellerFuchs** [comment]
@napcae Thanks for sending the patch  :)

**Pull request merged**
